### ISSUE TITLE
Optional Chromium light mode

### ISSUE THREAD

**Issue by Simonx22** [crybapp/portal#15]
I recently set Chromium to dark mode: https://github.com/crybapp/portal/pull/14
However, some people might prefer a light mode. Maybe we can have something in the .env file which removes the flag if the user wants a light mode.

**Comment by williamsthing** [comment]
Feature added in https://github.com/crybapp/portal/commit/8ec7b016bbcaa2c40df32aedeb5b0e73fac23e5e - closing this now!
