### ISSUE TITLE
Missing fonts for other languages

### ISSUE THREAD

**Issue by Simonx22** [crybapp/portal#17]
The VM doesn't support any Japanese characters (and likely other characters as well)

![image](https://user-images.githubusercontent.com/26326692/67069619-b8fde900-f14b-11e9-8b9b-ae7694912851.png)

**Comment by JeDaYoshi** [comment]
The current installation is so minimal we aren't even installing fonts except for the default ones - which for those kind of characters, won't work.

I'll take a look at this - thanks for reporting!
