### ISSUE TITLE
Old Chromium version

### ISSUE THREAD

**Issue by Simonx22** [crybapp/portal#18]
We currently install Chromium from apt, which is version 73. This version was released on March 12, 2019. The current release is version 77. For security reasons it's good to have the latest version. I will look into this later.

**Comment by Simonx22** [comment]
Apparently Chromium is outdated on apt and the package chromium-browser has no install candidate. We can switch to the normal Chrome to get the latest release. I have this running locally right now and didn't encounter any issues. The normal Chrome also supports a few more codecs than Chromium. Should I PR this change?

**Comment by JeDaYoshi** [comment]
I honestly prefer that we use Chromium - but thinking it support-side, it would be welcomed anyway. Feel free to - although I recommend you to make it after William merges the audio fix PR first.

If we're not going for Chrome for any reason, at least we should use another repository which have a more recent version.

**Comment by Simonx22** [comment]
I've looked into some repositories and most of them are either dead or updated only every few versions. Maybe there is a good repository that I missed though.

**Comment by Simonx22** [comment]
I'll make a PR for Google Chrome support after audio as been merged. In the future we could offer both Chrome and Firefox, something like a .env setting where you can choose which browser you want.

**Comment by williamsthing** [comment]
@Simonx22 Audio has been merged FYI 😄 https://github.com/crybapp/portal/pull/4

**Comment by Simonx22** [comment]
@williamsthing Will work on Google Chrome support now!

**Comment by JeDaYoshi** [comment]
We decided in stay with Chromium. 1421130 gives a more recent Chromium version as we updated the whole distro, anyway.
