### ISSUE TITLE
Remove minimise / expand / close buttons from Chromium header

### ISSUE THREAD

**Issue by williamsthing** [crybapp/portal#20]
Would be super neat if we could find a way to remove these buttons from the Chromium header. This window never needs to be closed so it's not required that we have those options there.

![image](https://user-images.githubusercontent.com/8293444/67134230-19069500-f209-11e9-91a1-e55e68785daf.png)

**Comment by JediMasterSoda** [comment]
I'm taking a look at this rn!

**Comment by JediMasterSoda** [comment]
This is possible by changing the openbox configuration but for some weird reason the window size shrinks. I could not find a way to fix the strange window size issue with other settings in the config.

I created an xml file for an openbox config and added the argument `--config-file=~/openbox_config.xml` to the openbox spawn command. 

**openbox_config.xml:**
```
<?xml version="1.0" encoding="UTF-8"?>
<openbox_config xmlns="http://openbox.org/3.4/rc">
    <applications>
        <application name="chrome">
            <decor>no</decor>
        </application>
    </applications>
</openbox_config>
```

**Comment by JeDaYoshi** [comment]
Done in #48. Closing!
