### ISSUE TITLE
VM does not run in it's own VPN with the Host

### ISSUE THREAD

**Issue by Chickenbreadlp** [crybapp/portal#26]
The Browser within the VM has direct access to every and all devices within the local Network of the Host.
This isn't that big of a deal on a VPS, but in the case of Self-Hosted Crybs, this behavior introduces a major security hole into the Network of the hoster.

**Comment by lnneth** [comment]
While I agree with you, if someone were to be self-hosting Cryb on their on personal computer I assume that they'd only be using it for one room at most, and with their trusted friends and such.

**Comment by Soliel** [comment]
I feel like this is a change that should be made in a network configuration, not something we should implement. Solving this issue can be done by running the portal in a Docker container with the right settings.
