### ISSUE TITLE
pulseaudio fails to start sometimes due to D-Bus name being already used

### ISSUE THREAD

**Issue by JeDaYoshi** [crybapp/portal#28]
Stopping all Docker instances (or Docker completely) seems to fix it, which is not convenient.

**Comment by williamsthing** [comment]
Are you good to take on this issue? @JeDaYoshi

**Comment by JeDaYoshi** [comment]
Yeah, I want to take a good look at it and probably remove the errors it says thar doesn't affects on anything.

**Comment by JeDaYoshi** [comment]
Actually. I haven't seen this happening again - and I mostly think it got fixed with the bf0a13d. I will close it for now.
