### ISSUE TITLE
Missing Browser Components Preventing Netflix From Playing

### ISSUE THREAD

**Issue by Beelnc** [crybapp/portal#43]
When trying to watch Netflix, you will get the following error: 

![netflixissue](https://user-images.githubusercontent.com/57054713/67629686-fbac7900-f84f-11e9-936c-528d6badffad.png)

When you go to chrome://components you will notice that the component they are talking about is not there: 

![componentlist](https://user-images.githubusercontent.com/57054713/67629693-28609080-f850-11e9-9164-60b41e7fbbe8.png)

**Comment by JeDaYoshi** [comment]
Yeah, Chromium is not supported by Netflix at all by default, as the component it asks for is not exactly free software, so you need to play up with it for it to work... or use Google Chrome directly.

I'll take a look anyway on what we can do.

**Comment by lxqueen** [comment]
The missing component is called Widevine - it's the DRM module that Chrome has. There is apparently a workaround to get it on Chromium though.

I haven't tested either of these two links, but they should help shed some light on methods to download the Widevine library outside of Chrome:
- https://www.andreafortuna.org/2019/09/24/how-to-install-latest-widevine-plugin-on-chromium/
- https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chromium-widevine

You may also need to update the *"Allow sites to play protected content"* setting value in `chrome://settings/content/protectedContent` after installation, according to the Arch wiki.

**Comment by JeDaYoshi** [comment]
Yeah, I saw that workaround, but we were unsure about it given it could be a problem given it's something that's not open-source, but given we need it for Netflix...

But then Netflix isn't exactly okay with this kind of stuff... More of a problem of _this will be okay?_ than how to implement it.

Still - given you'll surely want it, I'll take a final word with the team and see what we can do. Thanks anyway!

**Comment by JeDaYoshi** [comment]
(basically, given the license don't allow it to be distributed - and they being unsure if including into the Dockerfile etc. would be good to keep it being open source and if that'd not count as distributing - but it'll surely not...)

**Comment by williamsthing** [comment]
I think it's important we try include Widevine not just for Netflix support but for being able to support a fully functioning browser as a whole 👍

**Comment by NootThePenguin** [comment]
I ended up trying out chromium-widevine but unfortunately, it didn't work unless I'm doing something wrong? 

Lines I added to Dockerfile:

`RUN wget https://dl.google.com/widevine-cdm/1.4.9.1088-linux-x64.zip`
`RUN unzip 1.4.9.1088-linux-x64.zip`
`RUN sudo mv libwidevinecdm.so /usr/lib/chromium`
`RUN sudo chmod 644 /usr/lib/chromium/libwidevinecdm.so`

The outcome of this was "Your browser is no longer supported. Please upgrade ot try another browser."

![bNY38YLS](https://user-images.githubusercontent.com/50028329/68642119-fbacaa00-04da-11ea-9a41-bf65e3d59b26.png)

**Comment by JeDaYoshi** [comment]
Well, that's curious. I might need to give this more priority.

**Comment by plusreed** [comment]
That's actually really weird. When you install that, what version of Chromium is installed? I'm curious if Netflix detects if the browser is Chromium and just locks you out of the app (which could possibly be fixed with a user-agent string switch.)

**Comment by NootThePenguin** [comment]
> That's actually really weird. When you install that, what version of Chromium is installed? I'm curious if Netflix detects if the browser is Chromium and just locks you out of the app (which could possibly be fixed with a user-agent string switch.)

Chromium 78, I figured it out. #58

**Comment by plusreed** [comment]
Oh cool! Didn't notice that - will see if I can get someone to test it and make sure nothing got borked.
