### ISSUE TITLE
Only the guest is able to control the mouse of the VM

### ISSUE THREAD

**Issue by Simonx22** [crybapp/portal#6]
If I host a room and try to control the mouse it never works. However, if I give it to someone else it works fine.

**Comment by JeDaYoshi** [comment]
The workaround for it right now is refreshing, but it's not the ideal thing.

This issue should be in https://github.com/crybapp/web though.

**Comment by Simonx22** [comment]
Moved to https://github.com/crybapp/web/issues/13. Thanks!
