### ISSUE TITLE
Add option for other broswers.

### ISSUE THREAD

**Issue by intelfierce** [crybapp/portal#70]
Really now chromium is the only broswer and as you know many sites like netflix, hulu or disney++ doesn't work. So a good alternative would be to provide other options to use as broswer like use chrome or firefox. And I think rabb.it used to have firefox aswell?

**Comment by JeDaYoshi** [comment]
Hey there.

I am well aware of this and this was something I was going to do before, so users are able to choose between Chrome, Chromium, Firefox, and add other browsers etc. in case they want to.

That said, this counts as a duplicate for #53. Thanks anyway! I'll look into this later.
