### ISSUE TITLE
VM becomes laggy when I restart it a few times

### ISSUE THREAD

**Issue by Simonx22** [crybapp/portal#9]
When I create a VM manually, destroy it and create it again a few times it becomes very laggy. The only solution is to create a new room.

**Comment by williamsthing** [comment]
Does restarting `@cryb/aperture` help?

**Comment by Simonx22** [comment]
Nope, restarted ``@cryv/aperture`` and then ``@cryb/portal`` and it's still laggy

**Comment by williamsthing** [comment]
Will look into this when I get home!!

**Comment by JeDaYoshi** [comment]
Can't reproduce. Please open again if it still persists!
